---
- name: Install nginx
  apt: 
    name: nginx 
    state: present 
    update_cache: yes
    
- name: add site config 
  template:
    src: templates/big_nginx.conf.j2 
    dest: /etc/nginx/sites-enabled/default
    mode: '0755' 
    owner: root
    group: root

- name: restart nginx
  systemd:
    state: restarted
    daemon_reload: yes
    name: nginx
...