---
- name: Install MySQL
  apt:
    name: "{{ item }}" 
    state: latest
    update_cache: yes
  with_items:
    - python-pymysql
    - mysql-server
   # - python3-pip

- name: Copy the root credentials as .my.cnf file
  template:
    src: templates/my.cnf.j2
    dest: /root/.my.cnf
    owner: root
    mode: 0600
  notify:
    - restart mysql

- name: Create a new database
  mysql_db:
    name: todo_list
    state: present
  notify:
    - restart mysql

- name: Create user with all database privileges
  mysql_user:
    name: "{{ mysql_user }}"
    host: "%"
    password: "{{ mysql_pass }}"
    priv: '*.*:ALL,GRANT'
    state: present
  notify:
  - restart mysql

...